#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
trap 'echo "Error $? at $0:$LINENO" >&2' ERR

SUBM=.gitsubmodules

function git_init()
{
    git init
    git branch -m main
}

function git_add_config()
{
    git add .gitignore
    git add .gitattributes
    git commit -m 'chore: add .gitignore and .gitattributes'
}

function godot_add_project()
{
    git add .
    git commit -m 'chore: add project files'
}

function git_add_submodules()
{
    mkdir -p $SUBM
    pushd $SUBM
    
        git submodule add git@github.com:MikeSchulze/gdUnit4.git
        pushd gdUnit4
            git checkout v4.1.4
        popd

        git submodule add git@github.com:bitbrain/beehave.git
        pushd beehave
            git checkout v2.7.6
        popd
    
        git submodule add git@github.com:Ericdowney/SignalVisualizer.git
        pushd SignalVisualizer
            git checkout 1.3.0
        popd

        git submodule add git@github.com:coppolaemilio/dialogic.git
        pushd dialogic
            git checkout 2.0-alpha-10
        popd

    popd
    git add $SUBM/
    git commit -m 'chore: add addons submodules'
}

function gd_link_addons()
{
    mkdir -p addons
    ln -s ../$SUBM/gdUnit4/addons/gdUnit4 addons/
    ln -s ../$SUBM/beehave/addons/beehave addons/
    ln -s ../$SUBM/SignalVisualizer/addons/SignalVisualizer addons/
    ln -s ../$SUBM/dialogic/addons/dialogic addons/
    git add addons/
    git commit -m 'chore: link addons submodules'
}


git_init
git_add_config
godot_add_project
git_add_submodules
gd_link_addons  

